### ISSUE TITLE
Spatial domain labels

### ISSUE THREAD

**Issue by aaronkwc** [zhengli09/BASS-Analysis#2]
Hello,

For the analysis of various datasets, spatial domains were used to evaluate BASS's accuracy. However, I can't see it anywhere in the repo. For example, the mouse hypo data in "data/MERFISH_Animal1.RData" only has cell type labels but not the spatial domains. Would be helpful if the manual annotations are available somewhere, sorry in advance if I just missed it. Thanks!

Aaron

**Comment by zhengli09** [comment]
Hi Aaron,

Thanks for your interest in the BASS package. For the MERFISH data used in our paper, we only manually annotated the spatial domains for slides from Bregma-0.04 to Bregma-0.24 as this is a quite labor intensive process. You should be able to find the labels in a "z" column in "info_mult" for those slides in the data "data/MERFISH_Animal1.RData". 

Best,
Zheng

**Comment by aaronkwc** [comment]
Hi Zheng,

Thanks for the quick reply! I see it now, sorry for missing it.
